F5: handle HTML responses gracefully
The F5 iControl REST API sometimes returns error responses with HTML
payloads instead of JSON.  (This has been observed for HTTP 401 and 404
responses.) Gracefully handle such responses by ignoring the error and
response payload for HTTP 4xx and 5xx responses if decoding fails.

Before this commit, if the F5 iControl REST API returned an HTML response,
the rest_request method would return an error that rendered as follows:

    error: Decoder.Decode failed: invalid character '<' looking for beginning of value

After this commit the rest_request method will produce an error that
renders similar to the following:

    error: HTTP code: 401."

This commit fixes bug 1316463.

https://bugzilla.redhat.com/show_bug.cgi?id=1316463