template/router: explicitly handle "no child processes" error
When calling the router-reload script we would occasionally get:

```console
limiter.go:140 error reloading router: waitid: no child processes
```

In a CI run this could happen two/three times.

In cmd.Run() there is a potential race condition--the process is
started and then we wait for it. The process could complete and exit
before the call to wait because of, say, garbage collection.

We now explicitly swallow the error if it matches:
- wait: no child processes
- waitid: no child processes